import { db } from "./db.js";
import { activities } from "../shared/schema.js";

const seedActivities = [
  // TODDLER ACTIVITIES (2-3 years) - 10 activities
  {
    title: "Finger Paint Fun",
    materials: [
      { emoji: "🎨", name: "Washable finger paints" },
      { emoji: "📄", name: "Large paper" },
      { emoji: "🧽", name: "Wet wipes" },
    ],
    steps: [
      "Set up painting area with newspaper",
      "Let toddler explore colors with fingers",
      "Make handprints and simple shapes!",
    ],
    whyGreat: "Develops fine motor skills and sensory exploration perfect for toddlers.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["arts", "sensory", "messy", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "creative"],
    skillRequirements: null,
  },
  {
    title: "Big Sticker Art",
    materials: [
      { emoji: "⭐", name: "Large stickers" },
      { emoji: "📄", name: "Paper" },
      { emoji: "✏️", name: "Big crayons" },
    ],
    steps: [
      "Give toddler large stickers to peel and stick",
      "Help them create simple patterns",
      "Draw around stickers together!",
    ],
    whyGreat: "Perfect for developing pincer grasp and early artistic expression.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "20 min",
    tags: ["arts", "fine-motor", "easy", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Simple Playdough Fun",
    materials: [
      { emoji: "🧴", name: "Large playdough balls" },
      { emoji: "🥄", name: "Big plastic spoons" },
      { emoji: "🔪", name: "Large cookie cutters" },
    ],
    steps: [
      "Show toddler how to squeeze and poke playdough",
      "Make simple shapes together",
      "Press cookie cutters into dough!",
    ],
    whyGreat: "Strengthens little hands while providing sensory play.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "25 min",
    tags: ["sensory", "fine-motor", "creative", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["creative"],
    skillRequirements: null,
  },
  {
    title: "Bubble Pop Dance",
    materials: [
      { emoji: "💭", name: "Bubble machine or wands" },
      { emoji: "🎵", name: "Upbeat music" },
    ],
    steps: [
      "Blow bubbles while music plays",
      "Dance and try to pop bubbles",
      "Chase bubbles around the room!",
    ],
    whyGreat: "Combines movement with cause-and-effect learning.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["active", "music", "cause-effect", "toddler"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["music", "active"],
    skillRequirements: null,
  },
  {
    title: "Color Sorting Game",
    materials: [
      { emoji: "🔴", name: "Colorful objects" },
      { emoji: "🥣", name: "Colored bowls" },
    ],
    steps: [
      "Set out bowls in different colors",
      "Help toddler sort objects by color",
      "Celebrate each correct match!",
    ],
    whyGreat: "Teaches color recognition and sorting skills.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "20 min",
    tags: ["educational", "sorting", "colors", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Simple Water Play",
    materials: [
      { emoji: "💧", name: "Shallow water tub" },
      { emoji: "🥄", name: "Spoons and cups" },
      { emoji: "🦆", name: "Floating toys" },
    ],
    steps: [
      "Set up safe shallow water station",
      "Let toddler pour and splash gently",
      "Float toys and practice scooping!",
    ],
    whyGreat: "Provides calming sensory play while teaching basic physics.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "25 min",
    tags: ["sensory", "water-play", "calming", "toddler"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["sensory"],
    skillRequirements: null,
  },
  {
    title: "Big Book Storytime",
    materials: [
      { emoji: "📚", name: "Large picture books" },
      { emoji: "🛏️", name: "Cozy reading spot" },
    ],
    steps: [
      "Create comfortable reading nook",
      "Read with big expressions and voices",
      "Let toddler turn pages and point!",
    ],
    whyGreat: "Builds language skills and love of reading from early age.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["reading", "language", "quiet", "toddler"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["reading"],
    skillRequirements: null,
  },
  {
    title: "Musical Shakers",
    materials: [
      { emoji: "🥄", name: "Plastic bottles with rice" },
      { emoji: "🎵", name: "Simple music" },
    ],
    steps: [
      "Make simple shakers with sealed bottles",
      "Shake along to favorite songs",
      "Create rhythm patterns together!",
    ],
    whyGreat: "Develops rhythm sense and gross motor coordination.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "20 min",
    tags: ["music", "rhythm", "movement", "toddler"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["music"],
    skillRequirements: null,
  },
  {
    title: "Stack and Knock Down",
    materials: [
      { emoji: "🧱", name: "Large soft blocks" },
      { emoji: "⚽", name: "Soft ball" },
    ],
    steps: [
      "Build towers with large blocks",
      "Let toddler knock them down",
      "Rebuild and celebrate the crashes!",
    ],
    whyGreat: "Teaches cause-and-effect while developing hand-eye coordination.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "25 min",
    tags: ["building", "cause-effect", "coordination", "toddler"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["building"],
    skillRequirements: null,
  },
  {
    title: "Animal Sound Game",
    materials: [
      { emoji: "📱", name: "Animal pictures or book" },
    ],
    steps: [
      "Show picture of different animals",
      "Make animal sounds together",
      "Act out how animals move!",
    ],
    whyGreat: "Builds vocabulary and encourages imaginative play.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["animals", "sounds", "pretend-play", "toddler"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["animals"],
    skillRequirements: null,
  },

  // PRESCHOOL ACTIVITIES (3-4 years) - 10 activities
  {
    title: "Big Brush Painting",
    materials: [
      { emoji: "🖌️", name: "Large brushes" },
      { emoji: "🎨", name: "Washable paints" },
      { emoji: "📄", name: "Big paper" },
    ],
    steps: [
      "Set up painting station",
      "Show different brush strokes",
      "Create colorful abstract art!",
    ],
    whyGreat: "Develops arm control and color mixing understanding.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "30 min",
    tags: ["arts", "painting", "motor-skills", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Paper Tearing Art",
    materials: [
      { emoji: "📄", name: "Colored paper" },
      { emoji: "🖊️", name: "Glue stick" },
      { emoji: "📄", name: "Background paper" },
    ],
    steps: [
      "Tear paper into interesting shapes",
      "Arrange pieces to make pictures",
      "Glue down to create artwork!",
    ],
    whyGreat: "Builds hand strength without needing scissors skills.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "25 min",
    tags: ["arts", "fine-motor", "creative", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Shape Hunt Adventure",
    materials: [
      { emoji: "🔍", name: "Magnifying glass" },
      { emoji: "📝", name: "Shape cards" },
      { emoji: "📦", name: "Collection bag" },
    ],
    steps: [
      "Look for shapes around the house",
      "Match real objects to shape cards",
      "Collect items in special bag!",
    ],
    whyGreat: "Teaches shape recognition and observation skills.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "20 min",
    tags: ["educational", "shapes", "exploration", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Simple Science Mix",
    materials: [
      { emoji: "🥤", name: "Water and food coloring" },
      { emoji: "🥄", name: "Spoons for stirring" },
      { emoji: "🥤", name: "Clear containers" },
    ],
    steps: [
      "Add different colors to water",
      "Stir and watch colors change",
      "Mix colors to make new ones!",
    ],
    whyGreat: "Introduces basic science concepts and cause-and-effect.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "25 min",
    tags: ["science", "colors", "mixing", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Animal Movement Game",
    materials: [
      { emoji: "📱", name: "Animal sound app or book" },
      { emoji: "📄", name: "Animal pictures" },
    ],
    steps: [
      "Show picture of an animal",
      "Make the animal sound together",
      "Move and act like the animal!",
    ],
    whyGreat: "Develops gross motor skills and animal knowledge.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "20 min",
    tags: ["active", "animals", "pretend-play", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active", "animals"],
    skillRequirements: null,
  },
  {
    title: "Pretend Restaurant",
    materials: [
      { emoji: "📋", name: "Play menus and order pad" },
      { emoji: "🍽️", name: "Plastic dishes" },
      { emoji: "👨‍🍳", name: "Chef hat (optional)" },
    ],
    steps: [
      "Set up pretend restaurant area",
      "Take turns being chef and customer",
      "Create imaginative meals together!",
    ],
    whyGreat: "Develops social skills and imaginative play scenarios.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "35 min",
    tags: ["pretend-play", "social", "imagination", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["pretend-play"],
    skillRequirements: null,
  },
  {
    title: "Simple Puzzles Together",
    materials: [
      { emoji: "🧩", name: "Age-appropriate puzzles" },
      { emoji: "🏃‍♂️", name: "Patience and encouragement" },
    ],
    steps: [
      "Choose puzzles with 12-24 pieces",
      "Work together to find matching pieces",
      "Celebrate completion with high-fives!",
    ],
    whyGreat: "Develops problem-solving skills and patience.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "30 min",
    tags: ["puzzles", "problem-solving", "patience", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Garden Digging Fun",
    materials: [
      { emoji: "🥄", name: "Small shovels or spoons" },
      { emoji: "🌱", name: "Seeds or small plants" },
      { emoji: "💧", name: "Watering can" },
    ],
    steps: [
      "Find safe area to dig in soil",
      "Plant seeds or small plants together",
      "Water gently and talk about growing!",
    ],
    whyGreat: "Connects with nature while learning about plant life cycles.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "40 min",
    tags: ["outdoor", "nature", "gardening", "preschool"],
    energyLevel: "active",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["outdoor", "nature"],
    skillRequirements: null,
  },
  {
    title: "Basic Counting Games",
    materials: [
      { emoji: "🍎", name: "Countable objects (toys, snacks)" },
      { emoji: "📝", name: "Number cards 1-5" },
    ],
    steps: [
      "Count objects together up to 5",
      "Match number cards to object groups",
      "Practice counting in different ways!",
    ],
    whyGreat: "Builds early math foundation with concrete objects.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "20 min",
    tags: ["math", "counting", "numbers", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Indoor Obstacle Course",
    materials: [
      { emoji: "🛋️", name: "Pillows and cushions" },
      { emoji: "📏", name: "Tape for boundaries" },
    ],
    steps: [
      "Create safe obstacle course with furniture",
      "Show child how to navigate each obstacle",
      "Time attempts and cheer progress!",
    ],
    whyGreat: "Develops gross motor skills and following directions.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "30 min",
    tags: ["active", "gross-motor", "following-directions", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active"],
    skillRequirements: null,
  },

  // PRE-K ACTIVITIES (4-5 years) - 10 activities
  {
    title: "Scissor Skills Collage",
    materials: [
      { emoji: "✂️", name: "Child-safe scissors" },
      { emoji: "📰", name: "Magazines" },
      { emoji: "🖊️", name: "Glue stick" },
      { emoji: "📄", name: "Construction paper" },
    ],
    steps: [
      "Practice cutting along lines",
      "Cut out favorite pictures",
      "Arrange and glue to tell a story!",
    ],
    whyGreat: "Develops cutting skills and creative storytelling.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "35 min",
    tags: ["arts", "cutting", "storytelling", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Paper Airplane Contest",
    materials: [
      { emoji: "📄", name: "Different paper types" },
      { emoji: "✏️", name: "Crayons" },
      { emoji: "📏", name: "Ruler" },
    ],
    steps: [
      "Fold different airplane designs",
      "Decorate each plane uniquely",
      "Test which flies farthest!",
    ],
    whyGreat: "Combines art, science, and following directions.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "40 min",
    tags: ["arts", "science", "following-directions", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "science"],
    skillRequirements: null,
  },
  {
    title: "Kitchen Chemistry Lab",
    materials: [
      { emoji: "🥄", name: "Baking soda" },
      { emoji: "🍋", name: "Vinegar" },
      { emoji: "🎨", name: "Food coloring" },
      { emoji: "🧪", name: "Clear containers" },
    ],
    steps: [
      "Mix baking soda with colored vinegar",
      "Watch the fizzy reaction",
      "Try different color combinations!",
    ],
    whyGreat: "Introduces chemical reactions in a safe, fun way.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "30 min",
    tags: ["science", "chemistry", "reactions", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Number Hunt Game",
    materials: [
      { emoji: "🔢", name: "Number cards 1-10" },
      { emoji: "🏠", name: "Household objects to count" },
      { emoji: "📝", name: "Paper for recording" },
    ],
    steps: [
      "Pick a number card",
      "Find that many objects around house",
      "Count together and record findings!",
    ],
    whyGreat: "Makes math concrete and develops counting skills.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "25 min",
    tags: ["math", "counting", "exploration", "pre-k"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Advanced Obstacle Course",
    materials: [
      { emoji: "🛋️", name: "Furniture and pillows" },
      { emoji: "📏", name: "Tape for boundaries" },
      { emoji: "⏱️", name: "Timer" },
    ],
    steps: [
      "Design complex course together",
      "Practice each section safely",
      "Time runs and celebrate improvement!",
    ],
    whyGreat: "Develops planning skills and gross motor coordination.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "45 min",
    tags: ["active", "planning", "coordination", "pre-k"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active"],
    skillRequirements: null,
  },
  {
    title: "Simple Board Games",
    materials: [
      { emoji: "🎲", name: "Dice" },
      { emoji: "♟️", name: "Simple board games" },
    ],
    steps: [
      "Choose age-appropriate board games",
      "Practice taking turns patiently",
      "Celebrate good sportsmanship!",
    ],
    whyGreat: "Teaches strategy, patience, and social skills.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "35 min",
    tags: ["games", "strategy", "social-skills", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Beginning Writing Practice",
    materials: [
      { emoji: "✏️", name: "Large pencils" },
      { emoji: "📄", name: "Lined paper" },
      { emoji: "📚", name: "Letter practice books" },
    ],
    steps: [
      "Practice holding pencil correctly",
      "Trace letters and simple words",
      "Write own name with help!",
    ],
    whyGreat: "Develops writing readiness and letter recognition.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "25 min",
    tags: ["writing", "letters", "pre-literacy", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational", "writing"],
    skillRequirements: null,
  },
  {
    title: "Nature Scavenger Hunt",
    materials: [
      { emoji: "📝", name: "Picture checklist" },
      { emoji: "📦", name: "Collection bag" },
      { emoji: "🔍", name: "Magnifying glass" },
    ],
    steps: [
      "Create list of things to find outside",
      "Search together for each item",
      "Discuss what you discover!",
    ],
    whyGreat: "Encourages observation skills and nature appreciation.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "45 min",
    tags: ["outdoor", "nature", "observation", "pre-k"],
    energyLevel: "active",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["outdoor", "nature"],
    skillRequirements: null,
  },
  {
    title: "Cooking Simple Snacks",
    materials: [
      { emoji: "🍞", name: "Bread and spreads" },
      { emoji: "🔪", name: "Butter knife" },
      { emoji: "🍓", name: "Toppings" },
    ],
    steps: [
      "Wash hands and set up workspace",
      "Spread and arrange toppings together",
      "Enjoy your homemade creations!",
    ],
    whyGreat: "Teaches following directions and kitchen safety basics.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "30 min",
    tags: ["cooking", "following-directions", "life-skills", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["cooking"],
    skillRequirements: null,
  },
  {
    title: "Pattern Making Games",
    materials: [
      { emoji: "🔴", name: "Colored objects" },
      { emoji: "📝", name: "Pattern cards" },
    ],
    steps: [
      "Start simple patterns with colors",
      "Let child continue the pattern",
      "Create your own patterns together!",
    ],
    whyGreat: "Develops logical thinking and mathematical reasoning.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "25 min",
    tags: ["math", "patterns", "logic", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },

  // KINDERGARTEN ACTIVITIES (5-6 years) - 10 activities
  {
    title: "Comic Strip Creator",
    materials: [
      { emoji: "📄", name: "Comic template" },
      { emoji: "✏️", name: "Pencils" },
      { emoji: "🖍️", name: "Colored pencils" },
      { emoji: "📐", name: "Ruler" },
    ],
    steps: [
      "Plan story with beginning, middle, end",
      "Draw characters in comic panels",
      "Add dialogue and color scenes!",
    ],
    whyGreat: "Develops sequential thinking and storytelling skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "50 min",
    tags: ["arts", "storytelling", "sequence", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "reading"],
    skillRequirements: null,
  },
  {
    title: "Nature Art Collection",
    materials: [
      { emoji: "🍃", name: "Leaves and flowers" },
      { emoji: "🪨", name: "Smooth rocks" },
      { emoji: "🎨", name: "Paints" },
      { emoji: "🖌️", name: "Fine brushes" },
    ],
    steps: [
      "Collect beautiful nature items",
      "Create detailed painted designs",
      "Make gallery display of artwork!",
    ],
    whyGreat: "Connects art with nature and develops detailed artistic skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["arts", "nature", "detailed-work", "kindergarten"],
    energyLevel: "focused",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["arts", "outdoor"],
    skillRequirements: null,
  },
  {
    title: "Simple Board Game Design",
    materials: [
      { emoji: "📄", name: "Large cardboard" },
      { emoji: "🎲", name: "Dice" },
      { emoji: "♟️", name: "Game pieces" },
      { emoji: "✏️", name: "Markers" },
    ],
    steps: [
      "Design game board with path",
      "Create rules together",
      "Test and play the new game!",
    ],
    whyGreat: "Develops logical thinking and rule-following skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["games", "logic", "creativity", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Beginning Science Journal",
    materials: [
      { emoji: "📓", name: "Notebook" },
      { emoji: "✏️", name: "Pencils" },
      { emoji: "🔍", name: "Magnifying glass" },
      { emoji: "📐", name: "Ruler" },
    ],
    steps: [
      "Observe something interesting in detail",
      "Draw what you see carefully",
      "Write simple observations!",
    ],
    whyGreat: "Introduces scientific observation and recording skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "45 min",
    tags: ["science", "observation", "writing", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Advanced Building Challenge",
    materials: [
      { emoji: "🧱", name: "Various building blocks" },
      { emoji: "📏", name: "Measuring tools" },
      { emoji: "📄", name: "Planning paper" },
      { emoji: "📸", name: "Camera for documentation" },
    ],
    steps: [
      "Plan a complex structure design",
      "Build following your plan",
      "Measure and document creation!",
    ],
    whyGreat: "Develops spatial reasoning and planning ahead skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["building", "planning", "measuring", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["building"],
    skillRequirements: null,
  },
  {
    title: "Reading Together Time",
    materials: [
      { emoji: "📚", name: "Chapter books" },
      { emoji: "📖", name: "Reading comprehension questions" },
    ],
    steps: [
      "Choose engaging chapter books",
      "Take turns reading aloud",
      "Discuss story and characters!",
    ],
    whyGreat: "Builds reading fluency and comprehension skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "30 min",
    tags: ["reading", "comprehension", "fluency", "kindergarten"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["reading"],
    skillRequirements: null,
  },
  {
    title: "Math Word Problems",
    materials: [
      { emoji: "📝", name: "Simple word problems" },
      { emoji: "🧮", name: "Counting materials" },
      { emoji: "✏️", name: "Paper and pencil" },
    ],
    steps: [
      "Read word problems together",
      "Use objects to solve problems",
      "Write down the answers!",
    ],
    whyGreat: "Applies math skills to real-world scenarios.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "30 min",
    tags: ["math", "problem-solving", "real-world", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Strategy Board Games",
    materials: [
      { emoji: "♟️", name: "Chess, checkers, or similar" },
      { emoji: "📚", name: "Rule books" },
    ],
    steps: [
      "Learn rules of strategic games",
      "Practice thinking ahead",
      "Discuss different strategies!",
    ],
    whyGreat: "Develops critical thinking and strategic planning skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "45 min",
    tags: ["games", "strategy", "critical-thinking", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Creative Writing Stories",
    materials: [
      { emoji: "📝", name: "Story starters" },
      { emoji: "✏️", name: "Writing materials" },
      { emoji: "📚", name: "Illustration paper" },
    ],
    steps: [
      "Start with fun story prompts",
      "Write stories together",
      "Illustrate your favorite scenes!",
    ],
    whyGreat: "Develops creativity and writing skills simultaneously.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "50 min",
    tags: ["writing", "creativity", "storytelling", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["writing", "creative"],
    skillRequirements: null,
  },
  {
    title: "Advanced Science Experiments",
    materials: [
      { emoji: "🧪", name: "Safe experiment materials" },
      { emoji: "📓", name: "Lab notebook" },
      { emoji: "🔬", name: "Simple microscope" },
    ],
    steps: [
      "Set up controlled experiments",
      "Make predictions about results",
      "Record observations scientifically!",
    ],
    whyGreat: "Introduces scientific method and hypothesis testing.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["science", "experiments", "hypothesis", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },

  // EARLY ELEMENTARY ACTIVITIES (6-7 years) - 10 activities
  {
    title: "Photography Project",
    materials: [
      { emoji: "📸", name: "Digital camera or phone" },
      { emoji: "📓", name: "Photo journal" },
      { emoji: "✏️", name: "Writing materials" },
    ],
    steps: [
      "Choose interesting subjects to photograph",
      "Take photos from different angles",
      "Write captions describing each photo!",
    ],
    whyGreat: "Develops artistic eye and descriptive writing skills.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "60 min",
    tags: ["arts", "photography", "writing", "early-elementary"],
    energyLevel: "active",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Research Project Fun",
    materials: [
      { emoji: "📚", name: "Books and internet access" },
      { emoji: "📝", name: "Research worksheet" },
      { emoji: "🎨", name: "Presentation materials" },
    ],
    steps: [
      "Choose topic child is curious about",
      "Find information together",
      "Create presentation to share learning!",
    ],
    whyGreat: "Teaches research skills and information organization.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "90 min",
    tags: ["research", "presentation", "learning", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Complex Building Projects",
    materials: [
      { emoji: "🧱", name: "LEGOs or building sets" },
      { emoji: "📋", name: "Building instructions" },
      { emoji: "📏", name: "Measuring tools" },
    ],
    steps: [
      "Follow detailed building instructions",
      "Modify designs with own ideas",
      "Create instruction manual for others!",
    ],
    whyGreat: "Develops following complex directions and spatial reasoning.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "75 min",
    tags: ["building", "following-directions", "spatial", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["building"],
    skillRequirements: null,
  },
  {
    title: "Coding Without Computers",
    materials: [
      { emoji: "📋", name: "Algorithm cards" },
      { emoji: "🎯", name: "Target destination" },
      { emoji: "📝", name: "Step-by-step instructions" },
    ],
    steps: [
      "Create step-by-step instructions for tasks",
      "Follow exact sequences to reach goals",
      "Debug when instructions don't work!",
    ],
    whyGreat: "Introduces logical thinking and problem decomposition.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "45 min",
    tags: ["logic", "problem-solving", "sequencing", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Advanced Art Techniques",
    materials: [
      { emoji: "🎨", name: "Various art supplies" },
      { emoji: "📚", name: "Art technique books" },
      { emoji: "🖼️", name: "Examples of different styles" },
    ],
    steps: [
      "Learn about different art styles",
      "Practice specific techniques",
      "Create artwork in chosen style!",
    ],
    whyGreat: "Expands artistic knowledge and technical skills.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "60 min",
    tags: ["arts", "techniques", "styles", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Math Games Tournament",
    materials: [
      { emoji: "🎲", name: "Dice and cards" },
      { emoji: "📊", name: "Score sheets" },
      { emoji: "🏆", name: "Small prizes" },
    ],
    steps: [
      "Set up various math-based games",
      "Keep score and track progress",
      "Celebrate improvement and effort!",
    ],
    whyGreat: "Makes math practice fun and competitive.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "55 min",
    tags: ["math", "games", "competition", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational", "games"],
    skillRequirements: null,
  },
  {
    title: "Nature Documentation",
    materials: [
      { emoji: "📓", name: "Field journal" },
      { emoji: "🔍", name: "Magnifying glass" },
      { emoji: "📏", name: "Measuring tools" },
      { emoji: "📸", name: "Camera" },
    ],
    steps: [
      "Observe nature systematically",
      "Record detailed observations",
      "Create nature field guide!",
    ],
    whyGreat: "Develops scientific observation and documentation skills.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "75 min",
    tags: ["science", "observation", "documentation", "early-elementary"],
    energyLevel: "active",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["science", "nature"],
    skillRequirements: null,
  },
  {
    title: "Story Writing Workshop",
    materials: [
      { emoji: "📚", name: "Story structure guides" },
      { emoji: "✏️", name: "Writing materials" },
      { emoji: "🎨", name: "Illustration supplies" },
    ],
    steps: [
      "Plan story with clear structure",
      "Write detailed chapters",
      "Create illustrations and cover!",
    ],
    whyGreat: "Develops advanced writing and storytelling abilities.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "90 min",
    tags: ["writing", "storytelling", "illustration", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["writing", "creative"],
    skillRequirements: null,
  },
  {
    title: "Music Composition Basics",
    materials: [
      { emoji: "🎵", name: "Simple instruments" },
      { emoji: "📝", name: "Music notation paper" },
      { emoji: "🎹", name: "Keyboard or piano app" },
    ],
    steps: [
      "Learn basic music concepts",
      "Create simple melodies",
      "Record and share compositions!",
    ],
    whyGreat: "Introduces music theory and creative expression.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "50 min",
    tags: ["music", "composition", "creativity", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["music"],
    skillRequirements: null,
  },
  {
    title: "Geography Adventure",
    materials: [
      { emoji: "🗺️", name: "Maps and atlas" },
      { emoji: "📍", name: "Location markers" },
      { emoji: "📚", name: "Geography books" },
    ],
    steps: [
      "Explore different countries and cultures",
      "Plan imaginary travel itineraries",
      "Create cultural comparison charts!",
    ],
    whyGreat: "Develops global awareness and cultural appreciation.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "60 min",
    tags: ["geography", "culture", "exploration", "early-elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },

  // ADVANCED ELEMENTARY ACTIVITIES (7-8 years) - 10 activities
  {
    title: "Science Fair Project",
    materials: [
      { emoji: "🧪", name: "Experiment materials" },
      { emoji: "📊", name: "Data recording sheets" },
      { emoji: "📋", name: "Presentation board" },
    ],
    steps: [
      "Choose scientific question to investigate",
      "Design and conduct controlled experiment",
      "Present findings with evidence!",
    ],
    whyGreat: "Develops complete scientific method and presentation skills.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "120 min",
    tags: ["science", "experiments", "presentation", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Advanced Coding Projects",
    materials: [
      { emoji: "💻", name: "Computer or tablet" },
      { emoji: "📚", name: "Coding tutorials" },
      { emoji: "🎮", name: "Programming games" },
    ],
    steps: [
      "Learn basic programming concepts",
      "Create simple programs or games",
      "Debug and improve code!",
    ],
    whyGreat: "Introduces real programming and logical problem-solving.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "90 min",
    tags: ["coding", "programming", "logic", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Historical Timeline Project",
    materials: [
      { emoji: "📚", name: "History books and resources" },
      { emoji: "📅", name: "Timeline template" },
      { emoji: "🎨", name: "Art supplies for illustrations" },
    ],
    steps: [
      "Research historical period of interest",
      "Create detailed timeline with events",
      "Illustrate key moments in history!",
    ],
    whyGreat: "Develops research skills and historical understanding.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "100 min",
    tags: ["history", "research", "timeline", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Engineering Design Challenge",
    materials: [
      { emoji: "📐", name: "Engineering materials" },
      { emoji: "📋", name: "Design brief" },
      { emoji: "🔧", name: "Building tools" },
    ],
    steps: [
      "Define engineering problem to solve",
      "Design and test multiple solutions",
      "Iterate and improve final design!",
    ],
    whyGreat: "Introduces engineering design process and iterative thinking.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "110 min",
    tags: ["engineering", "design", "problem-solving", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["building", "science"],
    skillRequirements: null,
  },
  {
    title: "Book Club Discussion",
    materials: [
      { emoji: "📖", name: "Chapter books" },
      { emoji: "📝", name: "Discussion questions" },
      { emoji: "📋", name: "Reading journal" },
    ],
    steps: [
      "Read books independently",
      "Discuss themes and characters",
      "Write book reviews and recommendations!",
    ],
    whyGreat: "Develops critical thinking and literary analysis skills.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "60 min",
    tags: ["reading", "discussion", "analysis", "elementary"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["reading"],
    skillRequirements: null,
  },
  {
    title: "Advanced Math Problems",
    materials: [
      { emoji: "📊", name: "Complex word problems" },
      { emoji: "📐", name: "Mathematical tools" },
      { emoji: "🧮", name: "Calculator" },
    ],
    steps: [
      "Solve multi-step word problems",
      "Explain solution strategies",
      "Create own problems for others!",
    ],
    whyGreat: "Develops advanced mathematical reasoning and communication.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "50 min",
    tags: ["math", "problem-solving", "reasoning", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Creative Writing Portfolio",
    materials: [
      { emoji: "📚", name: "Writing prompts" },
      { emoji: "✏️", name: "Quality writing materials" },
      { emoji: "📁", name: "Portfolio folder" },
    ],
    steps: [
      "Write various types of stories and poems",
      "Edit and revise written work",
      "Compile best pieces into portfolio!",
    ],
    whyGreat: "Develops advanced writing skills and self-reflection.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "85 min",
    tags: ["writing", "editing", "portfolio", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["writing"],
    skillRequirements: null,
  },
  {
    title: "Cultural Research Project",
    materials: [
      { emoji: "🌍", name: "Cultural resources" },
      { emoji: "📋", name: "Research organizer" },
      { emoji: "🎨", name: "Presentation materials" },
    ],
    steps: [
      "Choose culture to study in depth",
      "Research traditions, food, and customs",
      "Create cultural presentation or display!",
    ],
    whyGreat: "Develops cultural awareness and research abilities.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "95 min",
    tags: ["culture", "research", "presentation", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Advanced Strategy Games",
    materials: [
      { emoji: "♟️", name: "Complex strategy games" },
      { emoji: "📚", name: "Strategy guides" },
      { emoji: "⏱️", name: "Game timer" },
    ],
    steps: [
      "Learn rules of advanced games",
      "Develop strategic thinking skills",
      "Analyze and improve gameplay!",
    ],
    whyGreat: "Develops advanced strategic thinking and planning skills.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "70 min",
    tags: ["games", "strategy", "analysis", "elementary"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Community Service Project",
    materials: [
      { emoji: "🤝", name: "Service project materials" },
      { emoji: "📋", name: "Planning worksheets" },
      { emoji: "📸", name: "Documentation tools" },
    ],
    steps: [
      "Identify community need to address",
      "Plan and execute service project",
      "Reflect on impact and experience!",
    ],
    whyGreat: "Develops empathy, planning skills, and civic responsibility.",
    ageRange: "7-8",
    minAge: 7,
    maxAge: 8,
    developmentStage: "elementary",
    duration: "150 min",
    tags: ["service", "community", "planning", "elementary"],
    energyLevel: "active",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["community"],
    skillRequirements: null,
  },

  // ADDITIONAL ACTIVITIES FOR BETTER FILTER COVERAGE (5-6 and 6-7 years)
  // More "calm" energy activities for 5-6 age group
  {
    title: "Quiet Reading Corner",
    materials: [
      { emoji: "📚", name: "Age-appropriate books" },
      { emoji: "🛏️", name: "Comfortable cushions" },
      { emoji: "🧸", name: "Favorite stuffed animal" },
    ],
    steps: [
      "Set up cozy reading space together",
      "Choose favorite books to explore",
      "Read quietly and discuss stories softly",
    ],
    whyGreat: "Develops reading skills and creates peaceful bonding time.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "30 min",
    tags: ["reading", "quiet", "bonding", "kindergarten"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["reading"],
    skillRequirements: null,
  },
  {
    title: "Mindful Drawing Session",
    materials: [
      { emoji: "✏️", name: "Colored pencils" },
      { emoji: "📄", name: "Sketch paper" },
      { emoji: "🧘", name: "Quiet space" },
    ],
    steps: [
      "Sit comfortably in quiet space",
      "Draw slowly and mindfully",
      "Focus on colors and gentle movements",
    ],
    whyGreat: "Promotes concentration and emotional regulation.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "25 min",
    tags: ["arts", "mindfulness", "quiet", "kindergarten"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Gentle Yoga and Stretching",
    materials: [
      { emoji: "🧘", name: "Yoga mat or towel" },
      { emoji: "🎵", name: "Calm music" },
      { emoji: "📱", name: "Simple pose guide" },
    ],
    steps: [
      "Practice simple animal poses together",
      "Focus on breathing and slow movements",
      "End with quiet relaxation time",
    ],
    whyGreat: "Develops body awareness and stress management skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "20 min",
    tags: ["movement", "mindfulness", "body-awareness", "kindergarten"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active"],
    skillRequirements: null,
  },
  // More "active" indoor activities for 5-6 age group
  {
    title: "Indoor Dance Party",
    materials: [
      { emoji: "🎵", name: "Upbeat music" },
      { emoji: "📱", name: "Speaker or device" },
      { emoji: "🎭", name: "Colorful scarves or ribbons" },
    ],
    steps: [
      "Play favorite energetic songs",
      "Dance freely with props",
      "Create dance moves together",
    ],
    whyGreat: "Burns energy while developing rhythm and creativity.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "20 min",
    tags: ["movement", "music", "creativity", "kindergarten"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active", "music"],
    skillRequirements: null,
  },
  {
    title: "Living Room Olympics",
    materials: [
      { emoji: "🏅", name: "Homemade medals" },
      { emoji: "🎯", name: "Soft objects for throwing" },
      { emoji: "📏", name: "Tape for marking" },
    ],
    steps: [
      "Set up safe indoor challenges",
      "Practice events like sock toss and jumping",
      "Award medals for participation",
    ],
    whyGreat: "Provides active play while building confidence.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "35 min",
    tags: ["active", "competition", "gross-motor", "kindergarten"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active"],
    skillRequirements: null,
  },
  // More "calm" activities for 6-7 age group
  {
    title: "Meditation and Breathing Games",
    materials: [
      { emoji: "🧘", name: "Comfortable seating" },
      { emoji: "🎵", name: "Soft background sounds" },
      { emoji: "🌺", name: "Visual focus object" },
    ],
    steps: [
      "Practice simple breathing techniques",
      "Use visual focus to stay calm",
      "Share feelings and thoughts quietly",
    ],
    whyGreat: "Teaches emotional regulation and mindfulness skills.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "15 min",
    tags: ["mindfulness", "emotional-regulation", "quiet", "early-elementary"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["mindfulness"],
    skillRequirements: null,
  },
  {
    title: "Quiet Puzzle Challenge",
    materials: [
      { emoji: "🧩", name: "Age-appropriate puzzles" },
      { emoji: "☕", name: "Comfortable workspace" },
      { emoji: "⏰", name: "Optional timer" },
    ],
    steps: [
      "Choose challenging but doable puzzle",
      "Work together slowly and patiently",
      "Celebrate completion with quiet pride",
    ],
    whyGreat: "Develops patience, problem-solving, and cooperation.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "40 min",
    tags: ["problem-solving", "patience", "cooperation", "early-elementary"],
    energyLevel: "calm",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  // More "active" indoor activities for 6-7 age group
  {
    title: "Indoor Scavenger Hunt",
    materials: [
      { emoji: "📝", name: "Hunt list with clues" },
      { emoji: "🏠", name: "Household items to find" },
      { emoji: "📱", name: "Timer for excitement" },
    ],
    steps: [
      "Create list of items to find around house",
      "Race to find items safely",
      "Check off items and celebrate finds",
    ],
    whyGreat: "Combines physical activity with problem-solving skills.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "30 min",
    tags: ["active", "problem-solving", "exploration", "early-elementary"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active", "educational"],
    skillRequirements: null,
  },
  {
    title: "Kitchen Dancing and Cooking",
    materials: [
      { emoji: "🎵", name: "Upbeat cooking playlist" },
      { emoji: "🥄", name: "Simple cooking ingredients" },
      { emoji: "👨‍🍳", name: "Child-safe cooking tools" },
    ],
    steps: [
      "Dance while preparing simple snacks",
      "Move to music between cooking steps",
      "Share snacks while continuing to groove",
    ],
    whyGreat: "Combines physical movement with life skills learning.",
    ageRange: "6-7",
    minAge: 6,
    maxAge: 7,
    developmentStage: "early-elementary",
    duration: "45 min",
    tags: ["active", "cooking", "music", "life-skills", "early-elementary"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active", "cooking"],
    skillRequirements: null,
  },
];

export async function seedDatabase() {
  console.log("Seeding database with activities...");
  
  const existingActivities = await db.select().from(activities).limit(1);
  if (existingActivities.length > 0) {
    console.log("Activities already exist, skipping seed...");
    return;
  }

  await db.insert(activities).values(seedActivities);
  console.log(`Seeded ${seedActivities.length} activities!`);
}