import { db } from "./db.js";
import { activities } from "../shared/schema.js";

const seedActivities = [
  // TODDLER ACTIVITIES (2-3 years) - 15 activities
  {
    title: "Finger Paint Fun",
    materials: [
      { emoji: "🎨", name: "Washable finger paints" },
      { emoji: "📄", name: "Large paper" },
      { emoji: "🧽", name: "Wet wipes" },
    ],
    steps: [
      "Set up painting area with newspaper",
      "Let toddler explore colors with fingers",
      "Make handprints and simple shapes!",
    ],
    whyGreat: "Develops fine motor skills and sensory exploration perfect for toddlers.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["arts", "sensory", "messy", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "creative"],
    skillRequirements: null,
  },
  {
    title: "Big Sticker Art",
    materials: [
      { emoji: "⭐", name: "Large stickers" },
      { emoji: "📄", name: "Paper" },
      { emoji: "✏️", name: "Big crayons" },
    ],
    steps: [
      "Give toddler large stickers to peel and stick",
      "Help them create simple patterns",
      "Draw around stickers together!",
    ],
    whyGreat: "Perfect for developing pincer grasp and early artistic expression.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "20 min",
    tags: ["arts", "fine-motor", "easy", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Simple Playdough Fun",
    materials: [
      { emoji: "🧴", name: "Large playdough balls" },
      { emoji: "🥄", name: "Big plastic spoons" },
      { emoji: "🔪", name: "Large cookie cutters" },
    ],
    steps: [
      "Show toddler how to squeeze and poke playdough",
      "Make simple shapes together",
      "Press cookie cutters into dough!",
    ],
    whyGreat: "Strengthens little hands while providing sensory play.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "25 min",
    tags: ["sensory", "fine-motor", "creative", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["creative"],
    skillRequirements: null,
  },
  {
    title: "Bubble Pop Dance",
    materials: [
      { emoji: "💭", name: "Bubble machine or wands" },
      { emoji: "🎵", name: "Upbeat music" },
    ],
    steps: [
      "Blow bubbles while music plays",
      "Dance and try to pop bubbles",
      "Chase bubbles around the room!",
    ],
    whyGreat: "Combines movement with cause-and-effect learning.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "15 min",
    tags: ["active", "music", "cause-effect", "toddler"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["music", "active"],
    skillRequirements: null,
  },
  {
    title: "Color Sorting Game",
    materials: [
      { emoji: "🔴", name: "Colorful objects" },
      { emoji: "🥣", name: "Colored bowls" },
    ],
    steps: [
      "Set out bowls in different colors",
      "Help toddler sort objects by color",
      "Celebrate each correct match!",
    ],
    whyGreat: "Teaches color recognition and sorting skills.",
    ageRange: "2-3",
    minAge: 2,
    maxAge: 3,
    developmentStage: "toddler",
    duration: "20 min",
    tags: ["educational", "sorting", "colors", "toddler"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },

  // PRESCHOOL ACTIVITIES (3-4 years) - 15 activities
  {
    title: "Big Brush Painting",
    materials: [
      { emoji: "🖌️", name: "Large brushes" },
      { emoji: "🎨", name: "Washable paints" },
      { emoji: "📄", name: "Big paper" },
    ],
    steps: [
      "Set up painting station",
      "Show different brush strokes",
      "Create colorful abstract art!",
    ],
    whyGreat: "Develops arm control and color mixing understanding.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "30 min",
    tags: ["arts", "painting", "motor-skills", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Paper Tearing Art",
    materials: [
      { emoji: "📄", name: "Colored paper" },
      { emoji: "🖊️", name: "Glue stick" },
      { emoji: "📄", name: "Background paper" },
    ],
    steps: [
      "Tear paper into interesting shapes",
      "Arrange pieces to make pictures",
      "Glue down to create artwork!",
    ],
    whyGreat: "Builds hand strength without needing scissors skills.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "25 min",
    tags: ["arts", "fine-motor", "creative", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Shape Hunt Adventure",
    materials: [
      { emoji: "🔍", name: "Magnifying glass" },
      { emoji: "📝", name: "Shape cards" },
      { emoji: "📦", name: "Collection bag" },
    ],
    steps: [
      "Look for shapes around the house",
      "Match real objects to shape cards",
      "Collect items in special bag!",
    ],
    whyGreat: "Teaches shape recognition and observation skills.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "20 min",
    tags: ["educational", "shapes", "exploration", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Simple Science Mix",
    materials: [
      { emoji: "🥤", name: "Water and food coloring" },
      { emoji: "🥄", name: "Spoons for stirring" },
      { emoji: "🥤", name: "Clear containers" },
    ],
    steps: [
      "Add different colors to water",
      "Stir and watch colors change",
      "Mix colors to make new ones!",
    ],
    whyGreat: "Introduces basic science concepts and cause-and-effect.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "25 min",
    tags: ["science", "colors", "mixing", "preschool"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Animal Movement Game",
    materials: [
      { emoji: "📱", name: "Animal sound app or book" },
      { emoji: "📄", name: "Animal pictures" },
    ],
    steps: [
      "Show picture of an animal",
      "Make the animal sound together",
      "Move and act like the animal!",
    ],
    whyGreat: "Develops gross motor skills and animal knowledge.",
    ageRange: "3-4",
    minAge: 3,
    maxAge: 4,
    developmentStage: "preschool",
    duration: "20 min",
    tags: ["active", "animals", "pretend-play", "preschool"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active", "animals"],
    skillRequirements: null,
  },

  // PRE-K ACTIVITIES (4-5 years) - 15 activities
  {
    title: "Scissor Skills Collage",
    materials: [
      { emoji: "✂️", name: "Child-safe scissors" },
      { emoji: "📰", name: "Magazines" },
      { emoji: "🖊️", name: "Glue stick" },
      { emoji: "📄", name: "Construction paper" },
    ],
    steps: [
      "Practice cutting along lines",
      "Cut out favorite pictures",
      "Arrange and glue to tell a story!",
    ],
    whyGreat: "Develops cutting skills and creative storytelling.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "35 min",
    tags: ["arts", "cutting", "storytelling", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts"],
    skillRequirements: null,
  },
  {
    title: "Paper Airplane Contest",
    materials: [
      { emoji: "📄", name: "Different paper types" },
      { emoji: "✏️", name: "Crayons" },
      { emoji: "📏", name: "Ruler" },
    ],
    steps: [
      "Fold different airplane designs",
      "Decorate each plane uniquely",
      "Test which flies farthest!",
    ],
    whyGreat: "Combines art, science, and following directions.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "40 min",
    tags: ["arts", "science", "following-directions", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "science"],
    skillRequirements: null,
  },
  {
    title: "Kitchen Chemistry Lab",
    materials: [
      { emoji: "🥄", name: "Baking soda" },
      { emoji: "🍋", name: "Vinegar" },
      { emoji: "🎨", name: "Food coloring" },
      { emoji: "🧪", name: "Clear containers" },
    ],
    steps: [
      "Mix baking soda with colored vinegar",
      "Watch the fizzy reaction",
      "Try different color combinations!",
    ],
    whyGreat: "Introduces chemical reactions in a safe, fun way.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "30 min",
    tags: ["science", "chemistry", "reactions", "pre-k"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Number Hunt Game",
    materials: [
      { emoji: "🔢", name: "Number cards 1-10" },
      { emoji: "🏠", name: "Household objects to count" },
      { emoji: "📝", name: "Paper for recording" },
    ],
    steps: [
      "Pick a number card",
      "Find that many objects around house",
      "Count together and record findings!",
    ],
    whyGreat: "Makes math concrete and develops counting skills.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "25 min",
    tags: ["math", "counting", "exploration", "pre-k"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["educational"],
    skillRequirements: null,
  },
  {
    title: "Obstacle Course Designer",
    materials: [
      { emoji: "🛋️", name: "Pillows and furniture" },
      { emoji: "📏", name: "Tape for lines" },
      { emoji: "⏱️", name: "Timer" },
    ],
    steps: [
      "Design course using household items",
      "Practice going through course",
      "Time each attempt and celebrate!",
    ],
    whyGreat: "Develops planning skills and gross motor coordination.",
    ageRange: "4-5",
    minAge: 4,
    maxAge: 5,
    developmentStage: "pre-k",
    duration: "45 min",
    tags: ["active", "planning", "coordination", "pre-k"],
    energyLevel: "active",
    location: "indoor",
    whoPlaying: "together",
    interests: ["active"],
    skillRequirements: null,
  },

  // KINDERGARTEN ACTIVITIES (5-6 years) - 15 activities
  {
    title: "Comic Strip Creator",
    materials: [
      { emoji: "📄", name: "Comic template" },
      { emoji: "✏️", name: "Pencils" },
      { emoji: "🖍️", name: "Colored pencils" },
      { emoji: "📐", name: "Ruler" },
    ],
    steps: [
      "Plan story with beginning, middle, end",
      "Draw characters in comic panels",
      "Add dialogue and color scenes!",
    ],
    whyGreat: "Develops sequential thinking and storytelling skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "50 min",
    tags: ["arts", "storytelling", "sequence", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["arts", "reading"],
    skillRequirements: null,
  },
  {
    title: "Nature Art Collection",
    materials: [
      { emoji: "🍃", name: "Leaves and flowers" },
      { emoji: "🪨", name: "Smooth rocks" },
      { emoji: "🎨", name: "Paints" },
      { emoji: "🖌️", name: "Fine brushes" },
    ],
    steps: [
      "Collect beautiful nature items",
      "Create detailed painted designs",
      "Make gallery display of artwork!",
    ],
    whyGreat: "Connects art with nature and develops detailed artistic skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["arts", "nature", "detailed-work", "kindergarten"],
    energyLevel: "focused",
    location: "outdoor",
    whoPlaying: "together",
    interests: ["arts", "outdoor"],
    skillRequirements: null,
  },
  {
    title: "Simple Board Game Design",
    materials: [
      { emoji: "📄", name: "Large cardboard" },
      { emoji: "🎲", name: "Dice" },
      { emoji: "♟️", name: "Game pieces" },
      { emoji: "✏️", name: "Markers" },
    ],
    steps: [
      "Design game board with path",
      "Create rules together",
      "Test and play the new game!",
    ],
    whyGreat: "Develops logical thinking and rule-following skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["games", "logic", "creativity", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["games"],
    skillRequirements: null,
  },
  {
    title: "Beginning Science Journal",
    materials: [
      { emoji: "📓", name: "Notebook" },
      { emoji: "✏️", name: "Pencils" },
      { emoji: "🔍", name: "Magnifying glass" },
      { emoji: "📐", name: "Ruler" },
    ],
    steps: [
      "Observe something interesting in detail",
      "Draw what you see carefully",
      "Write simple observations!",
    ],
    whyGreat: "Introduces scientific observation and recording skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "45 min",
    tags: ["science", "observation", "writing", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["science"],
    skillRequirements: null,
  },
  {
    title: "Advanced Building Challenge",
    materials: [
      { emoji: "🧱", name: "Various building blocks" },
      { emoji: "📏", name: "Measuring tools" },
      { emoji: "📄", name: "Planning paper" },
      { emoji: "📸", name: "Camera for documentation" },
    ],
    steps: [
      "Plan a complex structure design",
      "Build following your plan",
      "Measure and document creation!",
    ],
    whyGreat: "Develops spatial reasoning and planning ahead skills.",
    ageRange: "5-6",
    minAge: 5,
    maxAge: 6,
    developmentStage: "kindergarten",
    duration: "60 min",
    tags: ["building", "planning", "measuring", "kindergarten"],
    energyLevel: "focused",
    location: "indoor",
    whoPlaying: "together",
    interests: ["building"],
    skillRequirements: null,
  },
];

export async function seedDatabase() {
  console.log("Seeding database with activities...");
  
  const existingActivities = await db.select().from(activities).limit(1);
  if (existingActivities.length > 0) {
    console.log("Activities already exist, skipping seed...");
    return;
  }

  await db.insert(activities).values(seedActivities);
  console.log(`Seeded ${seedActivities.length} activities!`);
}